version: '3'

services:
  apache:
    image: httpd:2.4
    platform: linux/amd64
    ports:
      - "8800:80"
    volumes:
      - type: bind
        source: "./dist"
        target: "/usr/local/apache2/htdocs/"